language: csharp
dotnet: 2.0.0
dist: trusty
solution: HMS.sln
install:
 - nuget restore HMS.sln
 - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunners
script:
 - xbuild /p:Configuration=Relase HMS.sln
 - mono ./testrunners/xunit.runners.*/tools/xunit.console.clr4.exe ./*/bin/Release/*.Tests.dll
