language: csharp
dotnet: 3.1
dist: xenial
mono: latest
solution: HMS.sln
before_depoly:
 - cd ~
script:
 - "travis_wait 30 sleep 1800 &"
 - rm docker-compose.*
 - dotnet restore -r win-64x HMS.sln
 - dotnet build -r win-64x -c Release HMS.sln
 - sudo mkdir /app
 - sudo cp -r Web.Services/App_Data /app/App_Data
 - dotnet test HMS.sln -c Release --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover