language: csharp
dotnet: 2.2
dist: xenial
mono: latest
solution: HMS.sln
before_depoly:
 - cd ~
script:
 - "travis_wait 30 sleep 1800 &"
 - rm docker-compose.*
 - dotnet restore
 - dotnet build -c Release Data/
 - dotnet build -c Release Data.Simulate.AQUATOX/
 - dotnet build -c Release HMS.sln
 - dotnet build -c Release Web.Services/
 - dotnet build -c Release Web.Services.Tests/
 - sudo mkdir /app
 - sudo mkdir ~/Coverage
 - sudo cp -r Web.Services/App_Data /app/App_Data
 - sudo cp Web.Services/App_Data/* /home/travis/build/quanted/hms/Web.Services.Tests/bin/Release/netcoreapp2.2/
 - dotnet test Data.Tests/Data.Tests.csproj -c Release --verbosity=normal /nodeReuse:false --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - cp Data.Tests/coverage.opencover.xml ~/Coverage/DataTests.opencover.xml
 - dotnet test Web.Services.Tests/Web.Services.Tests.csproj -c Release --verbosity=normal /nodeReuse:false --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - cp Web.Services.Tests/coverage.opencover.xml ~/Coverage/WebServicesTests.opencover.xml
 - dotnet test Precipitation.Tests/Precipitation.Tests.csproj -c Release --verbosity=normal /nodeReuse:false --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - cp Precipitation.Tests/coverage.opencover.xml ~/Coverage/PrecipitationTest.opencover.xml
 - dotnet test OrganicMatter/OrganicMatter.AQUATOX.UnitTests/OrganicMatter.AQUATOX.UnitTests.csproj -c Release --verbosity=normal /nodeReuse:false --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - cp OrganicMatter/OrganicMatter.AQUATOX.UnitTests/coverage.opencover.xml ~/Coverage/OMAquatoxTests.opencover.xml
 - dotnet test Stream.Hydrology/AQUATOX.UnitTests/Stream.Hydrology.AQUATOX.UnitTests.csproj -c Release --verbosity=normal /nodeReuse:false --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - cp Stream.Hydrology/AQUATOX.UnitTests/coverage.opencover.xml ~/Coverage/SHAquatoxTests.opencover.xml
 - dotnet test Nutrients/Nutrients.AQUATOX.UnitTests/Nutrients.AQUATOX.UnitTests.csproj -c Release --verbosity=normal /nodeReuse:false --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - cp Nutrients/Nutrients.AQUATOX.UnitTests/coverage.opencover.xml ~/Coverage/NAquatoxTests.opencover.xml
 - sudo ls ~/Coverage 
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path ~/tools
 - ~/tools/csmacnz.Coveralls --opencover -i ~/Coverage --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID --serviceName "travis-ci"