language: csharp
dotnet: 2.2
dist: xenial
mono: latest
solution: HMS.sln
before_depoly:
 - cd ~
script:
 - "travis_wait 30 sleep 1800 &"
 - rm docker-compose.*
 - dotnet restore
 - dotnet build -c Release Data/
 - dotnet build -c Release Data.Simulate.AQUATOX/
 - dotnet build -c Release HMS.sln
 - dotnet build -c Release Web.Services/
 - dotnet build -c Release Web.Services.Tests/
 - sudo mkdir /app
 - sudo cp -r Web.Services/App_Data /app/App_Data
 - sudo cp Web.Services/App_Data/* /home/travis/build/quanted/hms/Web.Services.Tests/bin/Release/netcoreapp2.2/
 - dotnet test Data.Tests/Data.Tests.csproj -c Release --collect:"Code Coverage" /p:CollectCoverage=true  /p:CoverletOutputFormat=opencover
 - dotnet test Web.Services.Tests/Web.Services.Tests.csproj -c Release --collect:"Code Coverage" /p:CollectCoverage=true  /p:CoverletOutputFormat=opencover
 - dotnet test Precipitation.Tests/Precipitation.Tests.csproj -c Release --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - dotnet test OrganicMatter/OrganicMatter.AQUATOX.UnitTests/OrganicMatter.AQUATOX.UnitTests.csproj -c Release --collect:"Code Coverage" /p:CollectCoverage=true  /p:CoverletOutputFormat=opencover
 - dotnet test Stream.Hydrology/AQUATOX.UnitTests/Stream.Hydrology.AQUATOX.UnitTests.csproj -c Release --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - dotnet test Nutrients/Nutrients.AQUATOX.UnitTests/Nutrients.AQUATOX.UnitTests.csproj -c Release --collect:"Code Coverage"/p:CollectCoverage=true /p:CoverletOutputFormat=opencover 
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path ~/tools
after_success: 
 - ~/tools/csmacnz.Coveralls --multiple -i "opencover=Data.Tests/coverage.opencover.xml;opencover=Web.Services.Tests/coverage.opencover.xml;opencover=Precipitation.Tests/coverage.opencover.xml;opencover=OrganicMatter/OrganicMatter.AQUATOX.UnitTests/coverage.opencover.xml;opencover=Stream.Hydrology/AQUATOX.UnitTests/coverage.opencover.xml;opencover=Nutrients/Nutrients.AQUATOX.UnitTests/coverage.opencover.xml" --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID --serviceName "travis-ci"