language: csharp
dotnet: 2.0.0
dist: trusty
mono: none
solution: HMS.sln
script:
 - rm docker-compose.*
 - dotnet restore -nowarn:msb3202,nu1503
 - dotnet build -c Release
 - ls
 - cp /Web.Services/App_Data/url_info.txt /app/App_Data/url_info.txt
 - dotnet test *.Tests/*.Tests.csproj
