language: csharp
dotnet: 2.2.105
dist: xenial
mono: none
solution: HMS.sln
before_depoly:
 - cd ~
script:
 - "travis_wait 30 sleep 1800 &"
 - rm docker-compose.*
 - dotnet restore
 - dotnet build -c Release Data/
 - dotnet build -c Release Data.Simulate.AQUATOX/
 - dotnet build -c Release HMS.sln
 - dotnet build -c Release Web.Services/
 - dotnet build -c Release Web.Services.Tests/
 - sudo mkdir /app
 - sudo cp -r Web.Services/App_Data /app/App_Data
 - sudo cp Web.Services/App_Data/* /home/travis/build/quanted/hms/Web.Services.Tests/bin/Release/netcoreapp2.2/
 - dotnet test Data.Tests/Data.Tests.csproj -c Release
 - dotnet test Web.Services.Tests/Web.Services.Tests.csproj -c Release
 - dotnet test Precipitation.Tests/Precipitation.Tests.csproj -c Release
 - dotnet test OrganicMatter/OrganicMatter.AQUATOX.UnitTests/OrganicMatter.AQUATOX.UnitTests.csproj -c Release
 - dotnet test Stream.Hydrology/AQUATOX.UnitTests/Stream.Hydrology.AQUATOX.UnitTests.csproj -c Release
 - dotnet test Nutrients/Nutrients.AQUATOX.UnitTests/Nutrients.AQUATOX.UnitTests.csproj -c Release