language: csharp
dotnet: 3.1.202
mono: latest
solution: HMS.sln
sudo: required
before_install:
  - sudo apt-get install nuget
install:
  - travis_wait 60 mvn install
  - dotnet sln remove GUI/GUI.AQUATOX
  - dotnet sln remove GUI/GUI.AQUATOX.Electron
  - dotnet sln remove GUI/GUI.AQUATOX.Workflow
  - dotnet restore HMS.sln
before_depoly:
 - cd ~
script:
 - dotnet build -c Release HMS.sln
 - sudo mkdir /app
 - sudo cp -r Web.Services/App_Data /app/App_Data
 - dotnet test HMS.sln -c Release --collect:"Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover