language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
install:
 - dotnet restore
 - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
 - xbuild /p:Configuration=Release HMS.sln
 - mono ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./*.Tests/bin/Release/*.Tests.dll