language: csharp
dotnet: 2.0.0
dist: trusty
mono: none
solution: HMS.sln
script:
 - rm docker-compose.*
 - dotnet restore -nowarn:msb3202,nu1503
 - dotnet build -c Release
 - sudo mkdir /app
 - sudo cp -r Web.Services/App_Data /app/App_Data
 - dotnet test -c Release --filter "Priority=1"
