language: csharp
dotnet: 2.0.0
dist: trusty
mono: none
solution: HMS.sln
script:
 - dotnet restore -nowarn:msb3202,nu1503
 - rm docker-compose.*
 - dotnet build -c Release
 - mkdir /app/App_Data
 - cp -r Web.Services/App_Data /app/App_Data
 - dotnet test *.Tests/*.Tests.csproj
