language: csharp
dotnet: 2.0.0
dist: trusty
solution: HMS.sln
install:
 - nuget restore HMS.sln
 - nuget install xunit.runners -Version 2.3.1 -OutputDirectory HMS.UnitTests
script:
 - xbuild /p:Configuration=Relase HMS.sln
 - mono ./HMS.UnitTests/xunit.runners.*/tools/xunit.console.clr4.exe ./*/bin/Release/*.Tests.dll
