version: '3.4'
volumes: 
  collected_static: {}

services:
  web.services:
    image: webservices
    build:
      context: .
      dockerfile: Web.Services/Dockerfile
    volumes:
      - "./Web.Services/App_Data:/app/App_Data"