version: '3.4'
volumes: 
  collected_static: {}

services:
  web.services:
    image: webservices
    build:
      context: .
      dockerfile: Web.Services/Dockerfile
    volumes:
      - collected_static:/app/collected_static